import { splitInputInFields } from "./minesweeper";

const input = `4 4
*...
....
.*..
....
3 5
**...
.....
.*...
0 0`;

describe("Minesweeper", () => {
  describe("splitInputInFields()", () => {
    it("should return an array of two fields", () => {
      expect(splitInputInFields(input)).toStrictEqual([
        `*...
        ....
        .*..
        ....`,
        `**...
        .....
        .*...`,
      ]);
    });
  });
});
